### ISSUE TITLE
No provider for SASL mechanism GSSAPI: recompile librdkafka with libsasl2 or openssl support. Current build options: PLAIN SASL_SCRAM OAUTHBEARER (Rdkafka::Config::ClientCreationError)

### ISSUE THREAD

**Issue by bmonteiro** [appsignal/rdkafka-ruby#156]
Hello,

It is possible to get SASL_SSL supported by default ?

```
root@fluentd-x498r:~# cat rdkafka_producer_sasl_ssl.rb
require 'rdkafka'

config = {
        :"bootstrap.servers" => "localhost:9093",
        :"security.protocol" => "SASL_SSL",
        :"sasl.mechanisms" => "GSSAPI",
        :"sasl.kerberos.principal" => "XXX@ZZZZ.COM",
        :"sasl.kerberos.keytab" => "./xyz.keytab",
        :"ssl.ca.location" => "./ca",
        :"ssl.certificate.location"=> "./cert",
        :"ssl.key.location" => "./key",
        :"sasl.kerberos.service.name" => "kafka"
}

rdkafka = Rdkafka::Config.new(config)
producer = rdkafka.producer
producer.produce(topic: "testtopic", payload: "Hello World!").wait

root@fluentd-x498r:~# ruby rdkafka_producer_sasl_ssl.rb
Traceback (most recent call last):
	2: from rdkafka_producer_sasl_ssl.rb:20:in `<main>'
	1: from /usr/local/bundle/gems/rdkafka-0.8.1/lib/rdkafka/config.rb:142:in `producer'
/usr/local/bundle/gems/rdkafka-0.8.1/lib/rdkafka/config.rb:219:in `native_kafka': No provider for SASL mechanism GSSAPI: recompile librdkafka with libsasl2 or openssl support. Current build options: PLAIN SASL_SCRAM OAUTHBEARER (Rdkafka::Config::ClientCreationError)
root@fluentd-x498r:~#
```

**Comment by clutonik** [comment]
I am getting the same error. I am using fluentd's rdkafka2 output plugin which uses rdkafka. 
My Configuration:
<match syslog.**>
  @type rdkafka2
  # List of brokers
  brokers “#{ENV[‘KAFKA_BOOTSTRAP_SERVERS’]}”
  # ssl_ca_certs_from_system true
  ssl_ca_cert /app/ca-cert.pem
  use_event_time true
  principal “#{ENV[‘KAFKA_SASL_PRINCIPAL’]}”
  service_name kafka
  keytab /app/kafka.keytab
  get_kafka_client_log true
  # data type settings
  <format>
    @type json
  </format>
  # topic settings
  topic_key topic
  default_topic “#{ENV[‘KAFKA_TOPIC’]}”
  <buffer topic>
    flush_interval 5s
  </buffer>
  # producer settings
  required_acks -1
  compression_codec gzip
  @log_level trace
</match>

Error:
2021-04-18 03:41:59 +0000 [warn]: #0 Send exception occurred: No provider for SASL mechanism GSSAPI: recompile librdkafka with libsasl2 or openssl support. Current build options: PLAIN SASL_SCRAM OAUTHBEARER at /usr/local/bundle/gems/rdkafka-0.8.1/lib/rdkafka/config.rb:219:in `native_kafka'

I looked at few threads which talk about recompiling client libraries(rdkafka in this case) after reinstalling librdkafka-devel unix package. Reference: https://github.com/edenhill/librdkafka/issues/1776

**Comment by thijsc** [comment]
We don't use SASL ourselves, so haven't had a reason to add support myself. Happy to help with that though. I think the main bottleneck is having some way to test it. Does it require any changes on the Ruby side? Or just a different compilation option?

**Comment by bmonteiro** [comment]
I managed to have it working with CentOS (should work in any distro). It looks like it is all about the under-need lib "librdkafka" to be complied with SSL, GSSAPI support.

**Comment by clutonik** [comment]
@bmonteiro Can you share more details about how you tested it? 
@thijsc I am currently trying to test this by adding SASL_SSL listeners in the docker-compose configuration you have provided for local testing. I will update you whenever that's ready but if @bmonteiro has already got his test going then I think that would be great.

**Comment by thijsc** [comment]
>  I am currently trying to test this by adding SASL_SSL listeners in the docker-compose configuration you have provided for local testing.

That would be amazing!

**Comment by clutonik** [comment]
Created pull request for this. https://github.com/appsignal/rdkafka-ruby/pull/158#issue-625532329

**Comment by thijsc** [comment]
Looking at #158 I'm not sure we need a change in the library or installation code. Do we?

**Comment by thijsc** [comment]
Any update on this @clutonik?

**Comment by thijsc** [comment]
Closing this, feel free to reopen if there is news.

**Comment by johnisom** [comment]
Hi, with [zendesk/ruby-kafka](https://github.com/zendesk/ruby-kafka) now deprecated, would it be possible to re-open this issue?

**Comment by mensfeld** [comment]
@johnisom is something not working? If you compile rdkafka now with openssl, everything should work out of the box. Here's the setup (from Karafka but rdkafka underneath) instructions: https://karafka.io/docs/Deployment/#karafka-configuration-for-aws-msk-sasl-ssl

**Comment by mensfeld** [comment]
> The script itself works fine, but it is my case that requires enabling the curl library with the --enable-curl flag to support oauthbearer.

oauthbearers work without it as long as you implement the oauth handling yourself. You can take a look here: https://karafka.io/docs/Deployment/#custom-oauth-token-providers it works and it works with MSK. There are a lot of people using it. You do not need libcurl for that.

> You are still crafting a static version of the library, and then adding the necessary things from it to the dynamic one. 

The --whole-archive flag ensures all symbols from the static librdkafka are included, and then all the static dependency libraries are linked in to create a "self-contained" shared library.

And if you add curl flag most likely things will start to fail yes. I did not test this because i went with the assumption that libcurl is not needed for oauth (which is true) except some edge cases that I did not encounter.

You can always use this: https://github.com/karafka/rdkafka-ruby/blob/7552a05f1a89bcda5cafa753bb92c46e10631a06/ext/Rakefile#L14  and provide your own prerebuild librdkafka with whatever you need.

I have no plans including curl for your case at the moment as all of the use-cases this library is designed for are satisfied. I may however look into your PR if you submit one and evaluate it.

**Comment by yogrr** [comment]
I'm sorry, maybe I didn't point out the main thing - librdkafka needed with SASL/OAUTHBEARER by **OIDC** support. When using fluent-plugin-kafka and rdkafka in fluentd, it is necessary to rebuild librdkafka with libcurl and OpenSSL support for SASL/OAUTHBEARER, because without this, the librdkafka library user will receive the following logs in fluentd

```
{
    "time": "2025-09-09 12:32:34 +0000",
    "level": "error",
    "message": "unexpected error error_class=Rdkafka::Config::ConfigError error=\"Configuration property \\\"sasl.oauthbearer.client.id\\\" not supported in this build: OAuth/OIDC depends on libcurl and OpenSSL which were not available at build time\"",
    "worker_id": 0
}
```

Anyway, thanks for the help - I managed to rebuild librkafka for my own use. 

It seems that someone needs to start a PR in fluent-plugin-kafka so that they provide a way to use the librdkafka backend with full support for its functionality.
